package com.mpos.dto;

import com.mpos.commons.ConvertTools;

// default package
// Generated 2015-1-12 10:32:00 by Hibernate Tools 4.3.1

/**
 * MposDevice generated by hbm2java
 */
public class Tdevice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6277520631669631003L;
	private Integer id;
	private Integer table;
	private String tableName;
	private Boolean onlineStatus;
	private String dataVersion;
	private Long lastSyncTime;
	private Long lastReportTime;
	private Boolean status;
	private Long createTime;
	private Integer deviceType;
	private String channelId;
	private Integer storeId;
	
	@SuppressWarnings("unused")
	private String lastSyncTimeStr;
	@SuppressWarnings("unused")
	private String lastReportTimeStr;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getTable() {
		return table;
	}
	public void setTable(Integer table) {
		this.table = table;
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public Boolean getOnlineStatus() {
		return onlineStatus;
	}
	public void setOnlineStatus(Boolean onlineStatus) {
		this.onlineStatus = onlineStatus;
	}
	public String getDataVersion() {
		return dataVersion;
	}
	public void setDataVersion(String dataVersion) {
		this.dataVersion = dataVersion;
	}
	public Long getLastSyncTime() {
		return lastSyncTime;
	}
	public void setLastSyncTime(Long lastSyncTime) {
		this.lastSyncTime = lastSyncTime;
	}
	public Long getLastReportTime() {
		return lastReportTime;
	}
	public void setLastReportTime(Long lastReportTime) {
		this.lastReportTime = lastReportTime;
	}
	public Boolean getStatus() {
		return status;
	}
	public void setStatus(Boolean status) {
		this.status = status;
	}
	public Long getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
	public Tdevice(Integer id) {
		this.id = id;
	}
	public Tdevice() {}
	
	public Integer getDeviceType() {
		return deviceType;
	}
	public void setDeviceType(Integer deviceType) {
		this.deviceType = deviceType;
	}
	public String getChannelId() {
		return channelId;
	}
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}
	public String getLastSyncTimeStr() {
		return ConvertTools.longToDateString(lastSyncTime);
	}
	public void setLastSyncTimeStr(String lastSyncTimeStr) {
		this.lastSyncTimeStr = lastSyncTimeStr;
	}
	public String getLastReportTimeStr() {
		return ConvertTools.longToDateString(lastReportTime);
	}
	public void setLastReportTimeStr(String lastReportTimeStr) {
		this.lastReportTimeStr = lastReportTimeStr;
	}
	public Integer getStoreId() {
		return storeId;
	}
	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	
}
