package com.mpos.dto;
// default package
// Generated 2014-12-19 10:47:41 by Hibernate Tools 4.3.1

/**
 * MposLocalizedField generated by hbm2java
 */
public class TlocalizedField implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7818675890319116676L;
	private Integer localeId;
	private Tlanguage language;
	private Integer entityId;
	private String tableName;
	private String tableField;
	private String localeValue;

	public TlocalizedField() {
	}

	public TlocalizedField(Integer localeId, Tlanguage language,
			Integer entityId, String tableName, String tableField,
			String localeValue) {
		this.localeId = localeId;
		this.language = language;
		this.entityId = entityId;
		this.tableName = tableName;
		this.tableField = tableField;
		this.localeValue = localeValue;
	}





	public Integer getLocaleId() {
		return this.localeId;
	}

	public void setLocaleId(Integer localeId) {
		this.localeId = localeId;
	}

	public Tlanguage getLanguage() {
		return language;
	}

	public void setLanguage(Tlanguage language) {
		this.language = language;
	}

	public Integer getEntityId() {
		return entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableField() {
		return this.tableField;
	}

	public void setTableField(String tableField) {
		this.tableField = tableField;
	}

	public String getLocaleValue() {
		return this.localeValue;
	}

	public void setLocaleValue(String localeValue) {
		this.localeValue = localeValue;
	}


	

}
