package com.mpos.dto;

// Generated Dec 18, 2014 11:18:19 AM by Hibernate Tools 4.0.0

/**
 * MposProductRelease generated by hbm2java
 */
public class TproductRelease implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String products;
	private boolean isPublic;
	private Long publicTime;
	private Integer storeId;

	public TproductRelease() {
	}

	public TproductRelease(String products, boolean isPublic) {
		this.products = products;
		this.isPublic = isPublic;
	}

	public TproductRelease(String products, boolean isPublic, Long publicTime) {
		this.products = products;
		this.isPublic = isPublic;
		this.publicTime = publicTime;
	}

	public Integer getStoreId() {
		return storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProducts() {
		return this.products;
	}

	public void setProducts(String products) {
		this.products = products;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public Long getPublicTime() {
		return this.publicTime;
	}

	public void setPublicTime(Long publicTime) {
		this.publicTime = publicTime;
	}

}
