package com.mpos.dto;
// Generated 2015-1-12 10:32:00 by Hibernate Tools 4.3.1

/**
 * MposTable generated by hbm2java
 */
public class Ttable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5818707100284564654L;
	private Integer id;
	private String tableName;
	private Integer seatingNumber;
	private String descr="无";
	private Boolean status = true;
	private Long createTime = System.currentTimeMillis();
	private Integer storeId;

	
	public Ttable(String tableName, Integer seatingNumber, Integer storeId) {
		this.tableName = tableName;
		this.seatingNumber = seatingNumber;
		this.storeId = storeId;
	}

	public Ttable() {
	}

	public Ttable(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public Integer getSeatingNumber() {
		return seatingNumber;
	}

	public void setSeatingNumber(Integer seatingNumber) {
		this.seatingNumber = seatingNumber;
	}

	public String getDescr() {
		return descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Long getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	public Integer getStoreId() {
		return storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}
	
	
}
